declare module 'react-loadingg' {
	export const BoxLoading
	export const BlockLoading
	export const BlockReserveLoading
	export const BoxLoading
	export const CircleLoading
	export const CircleToBlockLoading
	export const CommonLoading
	export const DisappearedLoading
	export const LoopCircleLoading
	export const NineCellLoading
	export const TouchBallLoading
	export const TransverseLoading
	export const WaveLoading
	export const WaveTopBottomLoading
	export const WindMillLoading
	export const JumpCircleLoading
	export const MeteorRainLoading
	export const RotateCircleLoading
	export const StickyBallLoading
	export const SemipolarLoading
	export const SolarSystemLoading
	export const LadderLoading
	export const HeartBoomLoading
	export const RollBoxLoading
	export const RectGraduallyShowLoading
	export const PointSpreadLoading
	export const ThreeHorseLoading
	export const PassThrouthLoading
	export const CoffeeLoading
	export const BatteryLoading
	export const DiamonLoading
	export const EatLoading
}
